name: Main CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * 1'  # Tous les lundis à 2h du matin
  workflow_dispatch:  # Permet le déclenchement manuel

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  build-and-scan-docker:
    uses: ./.github/workflows/build-docker-image.yml
    secrets: inherit

  # ═══════════════════════════════════════════════
  # ÉTAPE 8 : PUBLICATION DOCKER HUB
  # ═══════════════════════════════════════════════
  publish-docker-hub:
    needs: [ build-and-scan-docker ]
    uses: ./.github/workflows/publish-docker-hub.yml
    secrets: inherit